// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iosdtunxezeccsfxvvqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvc2R0dW54ZXplY2NzZnh2dnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTc4NDYsImV4cCI6MjA3MTk5Mzg0Nn0.BE_9CiVKIUI9RJKyDlXVb1WwX2EanViRi9x4wDSsQ8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});